jobs:
  - job: x_test
    variables:
      - name: IMAGE_NAME
        value: ubuntu-18.04
      - group: certbot-common
    strategy:
      matrix:
        linux-py36:
          PYTHON_VERSION: 3.6
          TOXENV: py36
    pool:
      vmImage: $(IMAGE_NAME)
    steps:
      - template: ../steps/tox-steps.yml
