jobs:
  - job: snaps_build
    pool:
      vmImage: ubuntu-18.04
    timeoutInMinutes: 0
    variables:
      # Do not run the heavy non-amd64 builds for test branches
      ${{ if not(startsWith(variables['Build.SourceBranchName'], 'test-')) }}:
        ARCHS: amd64 arm64 armhf
      ${{ if startsWith(variables['Build.SourceBranchName'], 'test-') }}:
        ARCHS: amd64
    steps:
      - script: |
          sudo apt-get update
          sudo apt-get install -y --no-install-recommends snapd
          sudo snap install --classic snapcraft
        displayName: Install dependencies
      - task: UsePythonVersion@0
        inputs:
          versionSpec: 3.8
          addToPath: true
      - task: DownloadSecureFile@1
        name: credentials
        inputs:
          secureFile: launchpad-credentials
      - script: |
          git config --global user.email "$(Build.RequestedForEmail)"
          git config --global user.name "$(Build.RequestedFor)"
          mkdir -p ~/.local/share/snapcraft/provider/launchpad
          cp $(credentials.secureFilePath) ~/.local/share/snapcraft/provider/launchpad/credentials
          python3 tools/snap/build_remote.py certbot --archs ${ARCHS}
        displayName: Build snaps
      - script: |
          mv *.snap $(Build.ArtifactStagingDirectory)
        displayName: Prepare artifacts
      - task: PublishPipelineArtifact@1
        inputs:
          path: $(Build.ArtifactStagingDirectory)
          artifact: snaps
        displayName: Store snaps artifacts
