jobs:
  - job: snap_build
    strategy:
      matrix:
        amd64:
          ARCH: amd64
        arm64:
          ARCH: arm64
        armhf:
          ARCH: armhf
    pool:
      vmImage: ubuntu-18.04
    steps:
      - script: |
          snap/local/build.sh ${ARCH}
          mv *.snap $(Build.ArtifactStagingDirectory)
        displayName: Build Certbot snap
      - task: PublishPipelineArtifact@1
        inputs:
          path: $(Build.ArtifactStagingDirectory)
          artifact: snap-$(arch)
        displayName: Store snap artifact
