jobs:
  - job: test
    strategy:
      matrix:
        macos-py27:
          IMAGE_NAME: macOS-10.14
          PYTHON_VERSION: 2.7
          TOXENV: py27
    pool:
      vmImage: $(IMAGE_NAME)
    steps:
      - template: ../steps/tox-steps.yml
