jobs:
  - job: installer
    pool:
      vmImage: windows-latest
    steps:
      - task: UsePythonVersion@0
        inputs:
          versionSpec: 3.7
          architecture: x86
          addToPath: true
      - script: python windows-installer/construct.py
        displayName: Build Certbot installer
      - publish: $(System.DefaultWorkingDirectory)/windows-installer
        artifact: WindowsInstaller
      - script: python windows-installer/install.py
        displayName: Install Certbot
      - script: |
          python -m venv venv
          venv\Scripts\python tools\pip_install.py -e certbot-ci
        displayName: Prepare Certbot-CI
      - script: |
          set PATH=%ProgramFiles(x86)%\Certbot\bin;%PATH%
          venv\Scripts\python -m pytest certbot-ci\certbot_integration_tests\certbot_tests -n 4
        displayName: Run integration tests