jobs:
  - job: test
    pool:
      vmImage: vs2017-win2016
    strategy:
      matrix:
        py35:
          PYTHON_VERSION: 3.5
          TOXENV: py35
        py37-cover:
          PYTHON_VERSION: 3.7
          TOXENV: py37-cover
        integration-certbot:
          PYTHON_VERSION: 3.7
          TOXENV: integration-certbot
          PYTEST_ADDOPTS: --numprocesses 4
    steps:
    - task: UsePythonVersion@0
      inputs:
        versionSpec: $(PYTHON_VERSION)
        addToPath: true
    - script: python tools/pip_install.py -U tox coverage
      displayName: Install dependencies
    - script: python -m tox
      displayName: Run tox
