steps:
  - bash: |
      brew install augeas
    condition: startswith(variables['IMAGE_NAME'], 'macOS')
    displayName: Install MacOS dependencies
  - bash: |
      sudo apt-get update
      sudo apt-get install -y --no-install-recommends \
        python-dev \
        gcc \
        libaugeas0 \
        libssl-dev \
        libffi-dev \
        ca-certificates \
        nginx-light \
        openssl \
        expect
      sudo systemctl stop nginx
    condition: startswith(variables['IMAGE_NAME'], 'ubuntu')
    displayName: Install Linux dependencies
  - task: UsePythonVersion@0
    inputs:
      versionSpec: $(PYTHON_VERSION)
      addToPath: true
    condition: ne(coalesce(variables['PYTHON_VERSION'], 'UNSPECIFIED'), 'UNSPECIFIED')
  - bash: |
      python tools/pip_install.py -I tox virtualenv
    displayName: Install runtime dependencies
  - bash: |
      if [[ "${TOXENV}" == *"oldest"* ]]; then
        tools/run_oldest_tests.sh
      else
        python -m tox
      fi
    env:
      AWS_ACCESS_KEY_ID: $(AWS_ACCESS_KEY_ID)
      AWS_SECRET_ACCESS_KEY: $(AWS_SECRET_ACCESS_KEY)
    displayName: Run tox
