parameters:
- name: snapReleaseChannel
  type: string
  default: edge
  values:
  - edge
  - beta
- name: dockerTag
  type: string
  default: nightly

stages:
  - stage: Deploy
    jobs:
      - job: docker
        pool:
          vmImage: ubuntu-18.04
        steps:
          - task: Docker@2
            inputs:
              command: login
              containerRegistry: docker-hub
            displayName: Login to Docker Hub
          - bash: tools/docker/build.sh  ${{ parameters.dockerTag }}
            displayName: Build the Docker images
          - bash: tools/docker/deploy.sh ${{ parameters.dockerTag }}
            displayName: Deploy the Docker images
