parameters:
- name: snapReleaseChannel
  type: string
  default: edge
  values:
  - edge
  - beta

stages:
  - stage: Deploy
    jobs:
      - job: publish_docker
        pool:
          vmImage: ubuntu-18.04
        steps:
          - task: DownloadPipelineArtifact@2
            inputs:
              artifact: docker_images
              path: $(Build.SourcesDirectory)
            displayName: Retrieve Docker images
          - bash: docker load --input $(Build.SourcesDirectory)/docker_images.tar
          - task: Docker@2
            inputs:
              command: login
              # The credentials used here are for the shared certbotbot account
              # on Docker Hub. The credentials are stored in a service account
              # which was created by following the instructions at
              # https://docs.microsoft.com/en-us/azure/devops/pipelines/library/service-endpoints?view=azure-devops&tabs=yaml#sep-docreg.
              # The name given to this service account must match the value
              # given to containerRegistry below. "Grant access to all
              # pipelines" should also be checked.  To revoke these
              # credentials, we can change the password on the certbotbot
              # Docker Hub account or remove the account from the
              # Certbot organization on Docker Hub.
              containerRegistry: docker-hub
            displayName: Login to Docker Hub
          - bash: tools/docker/deploy.sh $(dockerTag)
            displayName: Deploy the Docker images
