stages:
  - stage: On_Failure
    jobs:
      - job: notify_mattermost
        pool:
          vmImage: ubuntu-latest
        steps:
          - bash: |
              MESSAGE="\
              ---\n\
              ##### Azure Pipeline
              *Repo* $(Build.Repository.ID) - *Pipeline* $(Build.DefinitionName) #$(Build.BuildNumber) - *Branch/PR* $(Build.SourceBranchName)\n\
              :warning: __Pipeline has failed__: [Link to the build](https://dev.azure.com/$(Build.Repository.ID)/_build/results?buildId=$(Build.BuildId)&view=results)\n\n\
              ---"
              echo ${MESSAGE}
    condition: failed()
