stages:
  - stage: On_Failure
    jobs:
      - job: notify_mattermost
        variables:
          - group: certbot-common
        pool:
          vmImage: ubuntu-latest
        steps:
          - bash: |
              curl https://example.org
    condition: failed()
