# Our full pipeline running all of our tests and deploying artifacts when
# appropriate.
trigger:
  # This prevents the problems described in
  # https://github.com/certbot/certbot/issues/8139.
  batch: true

  branches:
    include:
      - '*.x'
      # When changing these triggers, please ensure the documentation under
      # "Running tests in CI" is still correct.
      - test-*
  tags:
    include:
      - v*
pr: none
schedules:
  - cron: "30 4 * * *"
    displayName: Nightly build
    branches:
      include:
      - master
    always: true

variables:
  isTestBranch: ${{ startsWith(variables.Build.SourceBranchName, 'test-') }}
  onTag: ${{ startsWith(variables.Build.SourceBranch, 'refs/tags') }}

stages:
  - template: templates/stages/test-and-package-stage.yml
  # Only create a stripped down changelog on tags.
  - ${{ if eq(variables.onTag, 'true') }}:
    - template: templates/stages/changelog-stage.yml
  # Only deploy builds on tags or nightly builds.
  - ${{ if or(eq(variables.onTag, 'true'), eq(variables.Build.Reason, 'Schedule')) }}:
    - template: templates/stages/deploy-stage.yml
  # Don't send Mattermost messages about failures on test- branches.
  - ${{ if eq(variables.isTestBranch, 'false') }}:
    - template: templates/stages/notify-failure-stage.yml

