# Nightly pipeline running each day for master.
trigger: none
pr: none
schedules:
  - cron: "30 4 * * *"
    displayName: Nightly build
    branches:
      include:
      - master
    always: true

stages:
  - template: templates/stages/deploy-stage.yml
