# Nightly pipeline running each day for master.
trigger: none
pr: none
schedules:
  - cron: "* * * * *"
    displayName: Nightly build
    branches:
      include:
      - master
    always: true

stages:
  - template: templates/stages/test-and-package-stage.yml
