# Release pipeline to build and deploy Certbot for Windows for GitHub release tags
trigger:
  tags:
    include:
      - v*
pr: none

stages:
  - template: templates/stages/test-and-package-stage.yml
  - template: templates/stages/deploy-stage.yml
    parameters:
      snapReleaseChannel: beta
