# Release pipeline to run our full test suite, build artifacts, and deploy them
# for GitHub release tags.
trigger:
  tags:
    include:
      - v*
pr: none

stages:
  - template: templates/stages/deploy-stage.yml
    parameters:
      snapReleaseChannel: beta
      dockerTag: ${{variables['Build.SourceBranchName']}}
