name: Certbot PR build

on: [push, pull_request]

jobs:
  test:
    strategy:
      matrix:
        name:
          - ubuntu-py27
          - ubuntu-py35
          - ubuntu-py37
          - windows-py35
          - windows-py37
        include:
          - name: ubuntu-py27
            os: ubuntu
            python-version: 2.7
            toxenv: py27
          - name: ubuntu-py35
            os: ubuntu
            python-version: 3.5
            toxenv: py35
          - name: ubuntu-py37
            os: ubuntu
            python-version: 3.7
            toxenv: py37
          - name: windows-py35
            os: windows
            python-version: 3.5
            toxenv: py35
          - name: windows-py37
            os: windows
            python-version: 3.7
            toxenv: py37
      fail-fast: false
    runs-on: ${{ matrix.os }}-latest
    steps:
      - name: Checkout Certbot code
        uses: actions/checkout@v1
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v1
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies (Linux)
        run: |
          sudo apt install -y --no-install-recommends gcc libaugeas0 libssl-dev libffi-dev ca-certificates openssl nginx-light
          python tools/pip_install.py tox
        if: matrix.os == 'ubuntu'
      - name: Install dependencies (Windows)
        run: |
          python tools/pip_install.py tox
        if: matrix.os == 'windows'
      - name: Run tox
        run: python -m tox
        env:
          TOXENV: ${{ matrix.toxenv }}
          PYTEST_ADDOPTS: --numprocesses auto
